### ISSUE TITLE
[FEAT] Npx script for onboarding

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/studio#106]
#### Describe the feature
We should translate the steps in our setup into an npx script that you can run. It only needs to do 3 things:

1. Detect project framework (next vs vite vs webpack)
2. Install the appropriate npm packages
3. Update the relevant config files to use the plugins (e.g next.config.js)

**Comment by spartan-bachdkle** [comment]
Hi @Kitenite, I remember that we don't have an `onlook` plugin to generate `DATA_ONLOOK_ID` for React + ViteJs. Is that right?

**Comment by Kitenite** [comment]
Hey @spartan-bachdkle , 
Thank you for reaching out!  Correct, we do not have Vite.js support. The [webpack plugin](https://github.com/onlook-dev/studio/tree/main/plugins/babel) is in Babel so it should be portable to rollup ([example](https://www.npmjs.com/package/@rollup/plugin-babel#injected-helpers))

We have 2 issues related to onboarding Vite.js. Would you rather pick those up first?
Astro: https://github.com/onlook-dev/studio/issues/41
Remix: https://github.com/onlook-dev/studio/issues/46

**Comment by spartan-bachdkle** [comment]
Hey @Kitenite , I just finished the npx script for the NextJS project. I will pick that issue after finishing the npx script for CRA and webpack.

**Comment by Kitenite** [comment]
Woah that's awesome looking forward to seeing it!

**Comment by Kitenite** [comment]
@spartan-bachdkle so @bkrmendy is picking https://github.com/onlook-dev/studio/issues/109
I think it would be ready by the time you're done with the npx script for CRA and webpack :)

**Comment by spartan-bachdkle** [comment]
Hey @Kitenite, I can't push my `features/106-npx-script-for-onboarding` branch to the remote repository. Do I need to fork this project?

**Comment by Kitenite** [comment]
@spartan-bachdkle,
Yes, if you can fork and then open a PR from your fork that would be great!

**Comment by Kitenite** [comment]
@spartan-bachdkle you can see Vite support here :)
https://github.com/onlook-dev/studio/tree/main/demos/remix

**Comment by spartan-bachdkle** [comment]
@Kitenite I finished CRA, Next.js, and Webpack. Should I include Vite.js too?

**Comment by Kitenite** [comment]
Hey @spartan-bachdkle, 
Sorry I didn't see this before I finished the review.
I merged in the PR so could you add Vite.js support in a new one? The npx command can be `onlook` later on we'll add more sub commands under it

**Comment by spartan-bachdkle** [comment]
Hi @Kitenite, I will help you to add ViteJS support.

**Comment by Kitenite** [comment]
Just a heads-up I moved the folder and updated the package.json: https://github.com/onlook-dev/studio/pull/138

I also published the script to npm: https://www.npmjs.com/package/@onlook/cli

Awesome work!

**Comment by spartan-bachdkle** [comment]
Hi @Kitenite https://github.com/onlook-dev/studio/pull/155 please review this PR: add Vite framework support

**Comment by Kitenite** [comment]
Awesome approved and merged!

There are 2 pretty good ones:

1. https://github.com/onlook-dev/studio/issues/157
2. https://github.com/onlook-dev/studio/issues/91

Do you have a preference @spartan-bachdkle ?
