### ISSUE TITLE
[Bug] Performance is noticeably slow between design and interact mode

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/studio#116]
Users are reporting substantial lag between design and interact mode

**Comment by Kitenite** [comment]
Triaging, most likely due to blocking DOM processing taking a long time. Need to move the processing to a non-blocking async thread.

**Comment by Kitenite** [comment]
Should also only refresh part of the DOM that changes, not the entire dom when it is updated

**Comment by Kitenite** [comment]
Closing this for now but opened a follow-on issue for large DOM trees
https://github.com/onlook-dev/studio/issues/135
