### ISSUE TITLE
[Bug] Minor UI style improvements to the properties panel

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/studio#119]
This may be one of the easiest issues in history. Simply swap out some tailwind classes. 

- [ ] Some of the label colors in the properties panel don't match the default label color. They should be text-default, not white or text-active.
<img width="96" alt="image" src="https://github.com/user-attachments/assets/fa4f4695-3da7-40c6-9cd4-c5f40a9585ad">

- [ ] The input radii are mis-matched across a number of fields in the properties panel. They have rounded-sm, rounded, and rounded-md. Let's make all of them the standard "rounded" tailwind class.
<img width="162" alt="image" src="https://github.com/user-attachments/assets/9e7ec2a5-3236-4e89-a23b-c1d65097decd">

- [ ] inputs that are changeable should be "text-active" not "text-text" class so they're more noticeable to the user as something they can change. 
<img width="214" alt="image" src="https://github.com/user-attachments/assets/5e30c63b-5ac6-4e55-9176-68adf20813a9">

**Comment by SkyC0der** [comment]
Can I take it up then?

**Comment by drfarrell** [comment]
Absolutely! Go for it.

**Comment by SkyC0der** [comment]
Kindly review PR #130
