### ISSUE TITLE
[Bug] Gap input busted

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/studio#120]
#### Describe the bug

![Screenshot 2024-08-06 at 3 56 32 PM](https://github.com/user-attachments/assets/cd320230-811e-46ac-94fe-933582553202)

**Comment by drfarrell** [comment]
I was able to use the gap for the demo project – not sure how this busted gap situation happened but just throwing out that I was able to use the gap.

**Comment by Kitenite** [comment]
It's working a little weird where sometimes the unit write into the number field. Fixed.
