### ISSUE TITLE
[FEAT] Zoom hotkeys for improved usability for Mouse Users

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/studio#121]
Mostly requests from @nosajio
- [x] Hold down CMD or CTRL and scroll to zoom in and out of the canvas
- [x] Hold space and use the mouse to click and drag the page around. Holding space should be the hotkey for activating the "pan" activity in the bottom toolbar. When the user stops holding the space bar, it defaults to the normal clicking mode. Perhaps we throw some teal-400 in the background fill of the icon only while the spacebar hotkey is in use.
<img width="276" alt="Screenshot 2024-08-06 at 3 55 19 PM" src="https://github.com/user-attachments/assets/a4cdea53-b217-4c42-8dfc-5a587fa97266">

- [x] Add CMD + and CMD - for zooming in and out of the screen (Rather than changing the proportions of the elements on the page as would be expected in a normal browser)

**Comment by bkrmendy** [comment]
I implemented these on this PR: https://github.com/onlook-dev/studio/pull/148

**Comment by Kitenite** [comment]
Merged from @bkrmendy 's PR. Lovely stuff gang!
