### ISSUE TITLE
[Bug] Side panel developer mode opens on install of the app via command line

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/studio#156]
This side panel opens as a user opens the app, making it confusing as to what the Onlook experience is vs the electron app that it's built on. 

The expected behavior is for this to not be visible as the app is installed. 

<img width="1019" alt="Screenshot 2024-08-13 at 10 46 24 PM" src="https://github.com/user-attachments/assets/1077360b-9122-450d-bdd6-2f18349e220f">

**Comment by SkyC0der** [comment]
Could i take this up?

**Comment by Kitenite** [comment]
@SkyC0der go for it!

**Comment by SkyC0der** [comment]
![Screenshot 2024-08-16 012746](https://github.com/user-attachments/assets/b5daf23f-b314-46df-990f-b77173a00669)

Added a button to toggle the visibility state of the style tab. What do you think?

**Comment by SkyC0der** [comment]
![Screenshot 2024-08-16 013144](https://github.com/user-attachments/assets/02be8bca-981a-4187-8e74-5200d44d0802)

Made a PR on #166

**Comment by Kitenite** [comment]
Sorry this wasn't very clear. I believe @drfarrell meant the Chrome Devtool which should just be to remove this line
https://github.com/onlook-dev/studio/blob/main/app/electron/main/index.ts#L48

**Comment by SkyC0der** [comment]
Okay. Made a new commit here #166

**Comment by Kitenite** [comment]
Awesome, merged!
