### ISSUE TITLE
[Bug] Freezes on step 3 of install `npm install`

### ISSUE THREAD

**Issue by SeaDude** [onlook-dev/studio#36]
#### Describe the bug
I followed the Installation steps:
1. `git clone https://github.com/onlook-dev/studio.git`
2. `cd app`
3. `npm install`

Keeps freezing here. Tried multiple times. Even deleting and recloning...
```
PS me> git clone https://github.com/onlook-dev/studio.git
Cloning into 'studio'...
remote: Enumerating objects: 961, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (181/181), done.
Rremote: Total 961 (delta 137), reused 104 (delta 92), pack-reused 687eceiving objects:  98%

Receiving objects: 100% (961/961), 12.05 MiB | 29.10 MiB/s, done.
Resolving deltas: 100% (343/343), done.
PS me> cd .\studio\app\
PS me> npm install
[..................] / idealTree:app: sill idealTree buildDeps
```

Thoughts on this one?

**Comment by Kitenite** [comment]
Hey @SeaDude ,
How long did you let it run? I tested it with another machine and since its downloading electron it could take a long time. 
Can you try running with `npm install --verbose` and share the logs?

https://stackoverflow.com/questions/37038134/install-electron-on-node-for-windows-hangs

**Comment by Kitenite** [comment]
Closing since there's a potential solution. Please re-open if this issue still exists :)
