### ISSUE TITLE
[Draft] [FEAT] Welcome overlay 

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/studio#72]
#### Describe the feature
Add some infra for a welcome popup that shows up when you're new in the app. 
![Welcome Popup](https://github.com/user-attachments/assets/525dad59-db2b-4085-9aab-6b85e6659fc7)

**Comment by drfarrell** [comment]
I'll mock up something more Onlook-like but if anyone decides to pick this up, LMK!
